version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    networks:
      - messagebroker
  messagebroker.api:
    build:
      context: .
      dockerfile: src/MessageBroker.Publisher.WebApi/Dockerfile
    networks:
      - messagebroker
    depends_on:
      - rabbitmq
networks:
  messagebroker:
    driver: bridge